version: '3.8'

services:
  client:
    build:
      context: ./taskmanager.client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - api

  api:
    build:
      context: ./TaskManager.Server
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
      - '5001:8081'
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
